build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_LOGIN --password-stdin https://index.docker.io/v1/
    - docker build -t $DOCKERHUB_LOGIN/$DOCKER_NAME .
    - docker push $DOCKERHUB_LOGIN/$DOCKER_NAME

deploy:
  image: alpine:latest
  stage: deploy
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
  - eval $(ssh-agent -s)
  - echo "$VIRTUAL_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $VIRTUAL_IP >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
  - ssh $VIRTUAL_LOGIN@$VIRTUAL_IP "cd VK_HACK/ && docker-compose pull && docker-compose up -d"
  artifacts:
    paths:
    - public
