version: '3.8'

services:

  web:
    build: .
#    image: shureck/forcicd:latest
    restart: always
    depends_on:
        - mongodb

    command: uvicorn main:app --reload --host 0.0.0.0
    environment:
        - DB_URL=mongodb
        - DB_PORT=27017
    volumes:
        - ./zero_images/:/usr/src/zero_images/

    ports:
      - 8180:8000

  mongodb:
    image: mongo:latest
    container_name: docker-mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
      - 27018:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./docker_data/db:/data/db